Feat#68 register lesson/time slider
Gwasuwon-shot/Tutice_Client pull request #72
Opened 2023-07-14 15:30 UTC by parkheeddong

## 🔥 Related Issues

- close #68 

## 💙 작업 내용

- [x] ~ 시간 선택 구현

## ✅ PR Point

이전 회차 슬라이더와 유사합니다...!

오전, 오후 및 분단위는 스크롤이 이어지지 않게 설정을 변경했어요~!

StyledSwiper가 반복되는 부분이 있어서 map함수를 사용하려고 했지만
Swiper에 넘겨주는 옵션값이 달라서 함수없이 넣었습니다!

## 😡 Trouble Shooting

## 👀 스크린샷 / GIF / 링크
![image](https://github.com/Gwasuwon-shot/Tutice_Client/assets/116873401/de68fc7c-0405-4e3a-abda-e440164de49d)

2023-07-14 17:12 UTC, hae2ni reviewed
진짜 대박이야,,,,, 너무 멋있고,,,,,멋있어,,,,,,,,,

2023-07-14 17:19 UTC, seojisoosoo requested changes
우리 컨벤션 중에 하나가, const 변수 쫙 선언 -> let 변수 쫙 선언 -> function 함수 쫙 선언이었어용! 이 부분 지켜지면 좋을 것 같습니다!!

2023-07-14 17:19 UTC, seojisoosoo approved these changes

2023-07-14 17:31 UTC, merged

2023-07-14 20:57 UTC, parkheeddong commented on src/components/RegularLesson/TimePicker/DetailTimePicker.tsx
> +    const ampm = ['오전', '오후'];
반영했오요 고마워 💖

2023-07-17 00:27 UTC, eunbeann reviewed
라이브러리 넘 얌지게 잘섰네... 최고